// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ActivateLicenseKeyArgs = { key: string; instanceName: string }

export type ActivateLicenseKeyResponse = { isActivated: boolean; instanceId: string | null }

export type CompleteSessionArgs = { sessionId: string; wasCompleted: boolean }

export type CreateSessionArgs = { cycleId: string; sessionType: SessionType; durationMinutes: number }

export type DeactivateLicenseKeyArgs = { licenseKey: string; instanceId: string }

export type DeactivateLicenseKeyResponse = { isDeactivated: boolean }

export type GetPomodoroCycleWithRelationships = { id: string; status: Status; focusDuration: number; shortBreakDuration: number; longBreakDuration: number; sessionsUntilLongBreak: number; autoStartBreaks: boolean; autoStartPomodoros: boolean; startedAt: string; completedAt: string | null; updatedAt: string; sessions: PomodoroSession[] }

export type PomodoroCycle = { id: string; status: string; focus_duration: number; short_break_duration: number; long_break_duration: number; sessions_until_long_break: number; auto_start_breaks: boolean; auto_start_pomodoros: boolean; started_at: string; completed_at: string | null; updated_at: string }

export type PomodoroSession = { id: string; cycle_id: string; session_type: string; started_at: string; completed_at: string | null; duration_minutes: number; was_completed: boolean }

export type SessionType = "LONG_BREAK" | "FOCUS" | "SHORT_BREAK"

export type StartCycleArgs = { focusDuration: number; shortBreakDuration: number; longBreakDuration: number; sessionsUntilLongBreak: number; autoStartBreaks: boolean; autoStartPomodoros: boolean }

export type Status = "COMPLETED" | "IN_PROGRESS" | "ABANDONED"

export type UpdateCycleArgs = { id: string; status: Status }

export type ValidateLicenseKeyArgs = { licenseKey: string; instanceId: string }

export type ValidateLicenseKeyResponse = { isValid: boolean }

const ARGS_MAP = { '':'{"generate_checkout_session":[],"activate_license_key":["args"],"update_cycle_status":["args"],"start_pomodoro_cycle":["args"],"deactivate_license_key":["args"],"start_session":["args"],"get_current_cycle":[],"validate_license_key":["args"],"complete_session":["args"],"get_daily_stats":["date"]}' }
export type Router = { '': { generate_checkout_session: () => Promise<void>, 
activate_license_key: (args: ActivateLicenseKeyArgs) => Promise<ActivateLicenseKeyResponse>, 
validate_license_key: (args: ValidateLicenseKeyArgs) => Promise<ValidateLicenseKeyResponse>, 
deactivate_license_key: (args: DeactivateLicenseKeyArgs) => Promise<DeactivateLicenseKeyResponse>, 
start_pomodoro_cycle: (args: StartCycleArgs) => Promise<PomodoroCycle>, 
get_current_cycle: () => Promise<GetPomodoroCycleWithRelationships | null>, 
update_cycle_status: (args: UpdateCycleArgs) => Promise<PomodoroCycle>, 
start_session: (args: CreateSessionArgs) => Promise<PomodoroSession>, 
complete_session: (args: CompleteSessionArgs) => Promise<PomodoroSession>, 
get_daily_stats: (date: string) => Promise<number> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
