// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type CreateHabitArgs = { title: string; description: string; icon: string }

export type CreateHabitCompletionArgs = { id: string | null; habitId: string; createdAt: string | null }

export type GetHabitCompletionsArgs = { habitId: string; limit: number | null }

export type Habit = { id: string; title: string; description: string; icon: string; isArchived: boolean; updatedAt: string; createdAt: string }

export type HabitCompletion = { id: string; habitId: string; createdAt: string }

export type UpdateHabitArgs = { id: string; title: string | null; description: string | null; icon: string | null; isArchived: boolean | null }

const ARGS_MAP = { '':'{"update_habit":["args"],"create_habit":["args"],"delete_habit":["habit_id"],"get_habit_completions":["args"],"toggle_habit_completion":["args"],"get_archived_habits":[],"get_habit_completion_streak":["habit_id"],"get_active_habits":[]}' }
export type Router = { '': { create_habit: (args: CreateHabitArgs) => Promise<void>, 
get_active_habits: () => Promise<Habit[]>, 
get_archived_habits: () => Promise<Habit[]>, 
update_habit: (args: UpdateHabitArgs) => Promise<void>, 
delete_habit: (habitId: string) => Promise<void>, 
toggle_habit_completion: (args: CreateHabitCompletionArgs) => Promise<void>, 
get_habit_completions: (args: GetHabitCompletionsArgs) => Promise<HabitCompletion[]>, 
get_habit_completion_streak: (habitId: string) => Promise<number> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
